nginx:
  image: nginx
  ports:
    - "8080:80"
  volumes:
    - ./src:/var/www
    - ./src/nginx/default.conf.template:/etc/nginx/conf.d/default.conf
  links:
    - php

php:
  image: php:5.6.25-fpm
  volumes:
    - ./src/php-fpm/php-fpm.conf.template:/etc/php5/fpm/php-fpm.conf
    - ./src:/var/www
  working_dir: "/var/www/"

